config/routes.rb
Rails.application.routes.draw do

  devise_for :users
  get 'users/:username' => 'users#show', as: :user

  root to: "home#index"

  resources :posts, except: :destroy
  resources :search
  resources :phones

  resources :shelters do
    resources :shelter_photos,  only: [:create]
    resources :pets, only: [:new, :create]
    resources :comments, only: [:create]
    resources :staffs, only: [:create, :index]
  end
  resources :comments, only: [:destroy]
  resources :staffs, only: [:destroy]
  resources :shelter_photos,  only: [:destroy]
  patch '/shelter/set_photo/:photo_id' => 'shelters#set_photo'

  post '/getRegions'  => 'shelters#getRegions'
  post '/getCities'   => 'shelters#getCities'
  post '/getUsers'    => 'shelters#getUsers'

  resources :pets, only: [:show, :edit, :update] do
    resources :pet_photos,  only: [:create]
  end
  resources :pet_photos,  only: [:destroy]
  patch '/pet/set_photo/:photo_id' => 'pets#set_photo'

  get "/admin" => "admin/home#index"
  namespace :admin do

    get '/settings' => "settings#index"
    post '/generateSheltersJSON' => "settings#generateSheltersJSON"

    resources :users,     except: :destroy
    resources :shelters,  except: :destroy
    resources :pets,      except: :destroy

    post '/getRegions'  => 'shelters#getRegions'
    post '/getCities'   => 'shelters#getCities'

    get '/locations' => 'locations/countries#index'
    namespace :locations do
      resources :countries, except: [:destroy, :show]

      get '/regions/:country_id' => 'regions#index', as: :region
      get '/regions' => 'regions#index', as: :regions
      resources :regions, except: [:destroy, :index, :show]

      get '/cities/:region_id' => 'cities#index', as: :city
      get '/cities' => 'cities#index', as: :cities
      resources :cities, except: [:destroy, :index, :show]
    end
  end

  # SINGLE PAGES
  get '/terms'    => 'pages#terms'
  get '/about'    => 'pages#about'
  get '/sitemap'  => 'pages#sitemap'
  get '/press'    => 'pages#press'
  get '/contacts' => 'pages#contacts'
  post '/send_mail'    => 'pages#send_mail'
end

app/controllers/admin/home_controller.rb
class Admin::HomeController < Admin::ApplicationController

  def index
    @pets_count = Pet.count
    @shelters_count = Shelter.count
    @users_count = User.count
    @comments_count = Comment.count
  end

end

app/controllers/home_controller.rb
class HomeController < ApplicationController

  def index
    @geo = Geocoder.search(request.remote_ip)[0].data
    # @geo = Geocoder.search('37.214.53.180')[0].data
    @shelters_list = root_url + 'shelters.json'

    @geo['loc'] = @geo['loc'].split(',')
    @geo['latitude'] = @geo['loc'][0]
    @geo['longitude'] = @geo['loc'][1]
    
    @shelters = Shelter
      .select(:id, :title, :verified, :cover, "cities.title AS _city", "countries.title AS _country")
      .joins(:city, :country)
      .where(moderation: true, status: :active)
      .near([@geo['latitude'], @geo['longitude']], 12000, units: :km)
      .limit(4)

    @pets = Pet.select(:id, :name, :birthday, :avatar, :vaccination, :sterilization, :euthanasia, :subspecies, :shelter_id, "cities.title AS city", "countries.title AS country").joins(shelter: [:city, :country]).limit(4).order("pets.created_at DESC")
    render layout: "home_layout"
  end

end

app/helpers/admin/home_helper.rb
module Admin::HomeHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/_section_pets.html.haml
= link_to pet do
  .mb-2.card-loop.hover
    .col-12.col-md-12.col-lg-4.card-loop-image
      = image_tag pet.avatar.thumb.url
    .col-12.col-md-12.col-lg-8.card-loop-info
      %strong= pet.name
      %span
        = pet.country
        —
        = pet.city
      - if pet.euthanasia
        %span= pet.euthanasia.strftime("#{t('view.home.euthanasia')}: %m.%d.%Y")
      - if pet.birthday
        %span= pet.birthday.strftime("#{t('view.home.birthday')}: %d.%m.%Y")
      %div
        %span.badge.badge-warning
          = t "view.home.#{pet.subspecies}"
        - if pet.vaccination
          %span.badge.badge-info= t "view.home.vaccination"
        - if pet.sterilization
          %span.badge.badge-info= t "view.home.sterilization"

app/views/home/_section_shelters.html.haml
= link_to shelter do
  .mb-2.card-loop.hover
    .col-12.col-md-12.col-lg-4.card-loop-image
      = image_tag shelter.cover.thumb.url
    .col-12.col-md-12.col-lg-8.card-loop-info
      %strong= shelter.title
      %span
        = shelter._country
        —
        = shelter._city
      %div
        %span.badge.badge-secondary= t "view.home.shelter"
        - if shelter.verified
          %span.badge.badge-info= t "view.home.verified"

app/views/home/index.html.haml
= javascript_tag do
  var shelters        = "#{@shelters_list}",
  longitude           = "#{@geo['longitude']}",
  latitude            = "#{@geo['latitude']}";
#map.map
.container.mt-2
  = @shelter
  .row
    %section.col-md-6.col-12.mb-2.card-loops
      - @pets.each do |pet|
        = render partial: 'section_pets', locals:{pet: pet}
      = link_to t('view.home.other_pets'), search_index_path, class: "more_links"
    %section.col-md-6.col-12.mb-2.card-loops
      - @shelters.each do |shelter|
        = render partial: 'section_shelters', locals:{shelter: shelter}
      = link_to t('view.home.other_shelters'), shelters_path, class: "more_links"