config/routes.rb
Rails.application.routes.draw do

  devise_for :users
  get 'users/:username' => 'users#show', as: :user

  root to: "home#index"

  resources :posts, except: :destroy
  resources :search
  resources :phones

  resources :shelters do
    resources :shelter_photos,  only: [:create]
    resources :pets, only: [:new, :create]
    resources :comments, only: [:create]
    resources :staffs, only: [:create, :index]
  end
  resources :comments, only: [:destroy]
  resources :staffs, only: [:destroy]
  resources :shelter_photos,  only: [:destroy]
  patch '/shelter/set_photo/:photo_id' => 'shelters#set_photo'

  post '/getRegions'  => 'shelters#getRegions'
  post '/getCities'   => 'shelters#getCities'
  post '/getUsers'    => 'shelters#getUsers'

  resources :pets, only: [:show, :edit, :update] do
    resources :pet_photos,  only: [:create]
  end
  resources :pet_photos,  only: [:destroy]
  patch '/pet/set_photo/:photo_id' => 'pets#set_photo'

  get "/admin" => "admin/home#index"
  namespace :admin do

    get '/settings' => "settings#index"
    post '/generateSheltersJSON' => "settings#generateSheltersJSON"

    resources :users,     except: :destroy
    resources :shelters,  except: :destroy
    resources :pets,      except: :destroy

    post '/getRegions'  => 'shelters#getRegions'
    post '/getCities'   => 'shelters#getCities'

    get '/locations' => 'locations/countries#index'
    namespace :locations do
      resources :countries, except: [:destroy, :show]

      get '/regions/:country_id' => 'regions#index', as: :region
      get '/regions' => 'regions#index', as: :regions
      resources :regions, except: [:destroy, :index, :show]

      get '/cities/:region_id' => 'cities#index', as: :city
      get '/cities' => 'cities#index', as: :cities
      resources :cities, except: [:destroy, :index, :show]
    end
  end

  # SINGLE PAGES
  get '/terms'    => 'pages#terms'
  get '/about'    => 'pages#about'
  get '/sitemap'  => 'pages#sitemap'
  get '/press'    => 'pages#press'
  get '/contacts' => 'pages#contacts'
  post '/send_mail'    => 'pages#send_mail'
end

app/models/shelter.rb
class Shelter < ApplicationRecord
  include PublicActivity::Model
  # tracked only: [:create, :update], owner: Proc.new{|controller, model| p controller.current_user}

  mount_uploader :cover, ShelterCoverUploader

  belongs_to  :user
  belongs_to  :country
  belongs_to  :city
  belongs_to  :region

  has_many    :pets, dependent: :destroy
  has_many    :shelter_photos, dependent: :destroy
  has_many    :shelter_staffs, dependent: :destroy
  has_many    :schedules, dependent: :destroy, autosave: true
  has_many    :phones, dependent: :destroy, autosave: true
  has_many    :comments, as: :commentable

  enum status: [:active, :suspended, :deactived]

  accepts_nested_attributes_for :schedules, reject_if: lambda{|attributes| attributes[:open].blank? || attributes[:close].blank?}, allow_destroy: true
  accepts_nested_attributes_for :phones, allow_destroy: true

  validates :user_id, numericality: true
  validates :user_id, :title, presence: true
  validates :country_id, :region_id, :city_id, presence: true
  validates :country_id, :region_id, :city_id, numericality: true

  geocoded_by :address, lookup: lambda{|obj| obj.geocoder_lookup}
  after_validation :geocode

  def address
    [house_number, street, city.title, region.title, country.title].compact.reject(&:empty?).join(', ')
  end

  def geocoder_lookup
    country.lookup_code.to_sym
  end

end

app/controllers/admin/shelters_controller.rb
class Admin::SheltersController < Admin::ApplicationController
  helper_method :sort_column, :sort_direction

  def index
    @shelters = Shelter.order(sort_column + ' ' + sort_direction).includes(:country, :user)
  end

  def edit
    @shelter = Shelter.includes(:country).find(params[:id])
    @countries = Country.where(id: @shelter.country_id)
    @regions = Region.where(id: @shelter.region_id)

    7.times do |i|
      day = @shelter.schedules.day_of_weeks.key(i)
      unless @shelter.schedules.any?{|j| j.day_of_week == day}
        @shelter.schedules.build(day_of_week: day)
      end
    end

    @schedules = @shelter.schedules.sort_by do |a|
      @shelter.schedules.day_of_weeks[a.day_of_week]
    end

    authorize [:admin, @shelter]
  end

  def update
    @shelter = Shelter.find(params[:id])
    @shelter.update_attributes(shelter_params)

    if @shelter.errors.empty?
      redirect_to admin_shelters_path
    else
      p @shelter.errors
      render "edit"
    end
  end

  def getRegions
    @regions = Region.where(country_id: params[:country_id]).select(:id, :title)
    render json: @regions
  end

  def getCities
    @city = City.where(region_id: params[:region_id]).select(:id, :title)
    render json: @city
  end

  private

  def sort_column
    Shelter.column_names.include?(params[:sort]) ? params[:sort] : 'id'
  end

  def sort_direction
    %w[asc desc].include?(params[:direction]) ? params[:direction] : 'asc'
  end

  def shelter_params
    params.require(:shelter).permit(:title, :street, :house_number, :latitude, :longitude, :about, :cover, :moderation, :verified, :country_id, :region_id, :city_id, :status, :photo, schedules_attributes:[:open, :close, :day_of_week, :work_day, :id], phones_attributes:[:phone_number, :name, :_destroy, :id])
  end
end

app/controllers/shelters_controller.rb
class SheltersController < ApplicationController
  before_action :authenticate_user!,  only: [:new, :create, :edit, :update]
  before_action :find_shelter,        only: [:show, :edit, :update]

  def index
    @search = Shelter.includes(:city, :country).where(moderation: true, status: :active).search(params[:q])
    @shelters = @search.result.paginate(page: params[:page], per_page: 10)
    @countries = params[:q][:countries_eq] if params[:q] && params[:q][:countries_eq]
  end

  def show
    @pets = Pet.select(:id, :name, :birthday, :avatar, :vaccination, :sterilization, :euthanasia, :subspecies, :shelter_id, "cities.title AS city", "countries.title AS country").joins(shelter: [:city, :country]).where(shelter_id: @shelter.id).limit(5).order("pets.created_at DESC")

    @comment = Comment.new
    @comments = @shelter.comments.order('created_at desc').includes(:user)

    @schedules = @shelter.schedules.sort_by do |a|
      @shelter.schedules.day_of_weeks[a.day_of_week]
    end
  end

  def edit
    7.times do |i|
      day = @shelter.schedules.day_of_weeks.key(i)
      unless @shelter.schedules.any?{|j| j.day_of_week == day}
        @shelter.schedules.build(day_of_week: day)
      end
    end

    @schedules = @shelter.schedules.sort_by do |a|
      @shelter.schedules.day_of_weeks[a.day_of_week]
    end
  end

  def update
    @shelter.update_attributes(shelter_params)

    # DELETE DAYS WITH BLANK TIME
    params[:shelter][:schedules_attributes].each do |key, value|
      if value[:id]
        Schedule.find(value[:id]).destroy  if value[:open].blank? || value[:close].blank?
      end
    end

    if @shelter.errors.empty?
      redirect_to @shelter
    else
      p @shelter.errors
      render "edit"
    end
  end

  def new
    @shelter    = Shelter.new
    @countries  = Country.all

    @schedules = []
    7.times{ |i|
      day = @shelter.schedules.day_of_weeks.key(i)
      @schedules << @shelter.schedules.build(day_of_week: day)
    }
    authorize @shelter
  end

  def create
    @shelter = Shelter.new(shelter_params)
    authorize @shelter

    @shelter.user_id = current_user.id
    @shelter.save

    if @shelter.errors.empty?
      flash[:success] = "Shelter added!"
      redirect_to @shelter
    else
      @shelter.country = nil
      flash.now[:error] = "You have error!"
      render :new
    end
  end

  def getRegions
    @regions = Region.where(country_id: params[:country_id]).select(:id, "title")
    render json: @regions
  end

  def getCities
    @city = City.where(region_id: params[:region_id]).select(:id, "title")
    render json: @city
  end

  def getUsers
    @users = User.all.select(:id, :username).order(username: :desc)
    render json: @users
  end

  def addStaff
    @shelter = Shelter.find(shelter_staff_params[:shelter_id])
    @staff = @shelter.shelter_staffs.create(shelter_staff_params)
    render json: @staff
  end

  def deleteStaff
    @staff = ShelterStaff.where(
      user_id: shelter_staff_params[:user_id],
      shelter_id: shelter_staff_params[:shelter_id]
    )
    @staff.destroy_all
  end

  def set_photo
    @shelter_photo = ShelterPhoto.find(params[:photo_id])
    @shelter = Shelter.find(@shelter_photo.shelter_id)
    authorize @shelter

    @shelter.update_column(:cover, @shelter_photo.title_identifier)
  end

  private

  def shelter_params
    params.require(:shelter).permit(:title, :street, :house_number, :latitude, :longitude, :about, :cover, :moderation, :verified, :country_id, :region_id, :city_id, :status, :photo, phones_attributes:[:phone_number, :name, :_destroy, :id], schedules_attributes:[:open, :close, :day_of_week, :work_day, :id])
  end

  def shelter_staff_params
    params.permit(:shelter_id, :user_id, :role)
  end

  def find_shelter
    @shelter = Shelter.select("shelters.*, countries.title AS country_title, regions.title AS region_title, cities.title AS city_title").joins(:country, :region, :city).find(params[:id])
    authorize @shelter
  end

end

app/helpers/admin/shelters_helper.rb
module Admin::SheltersHelper
end

app/helpers/shelters_helper.rb
module SheltersHelper
end

app/views/admin/shelters/_fields_address.html.haml
= f.association :country, label_method: :title, value_method: :id, include_blank: true
= f.input :region_id, collection: @countries, as: :grouped_select, group_method: :regions, label_method: :title, include_blank: false, selected: @shelter.region_id, group_label_method: :title
= f.input :city_id, collection: @regions, as: :grouped_select, group_method: :cities, include_blank: false, label_method: :title, selected: @shelter.city_id, group_label_method: :title
%fieldset.mb-2
  .input-group
    .input-group-prepend
      %span.input-group-text= fa_icon "home"
    = f.input_field :street, label: false, placeholder: t('view.shelter.street'), class: "form-control"
    = f.input_field :house_number, label: false, placeholder: t('view.shelter.house-number'), class: "form-control"
  .input-group
    .input-group-prepend
      %span.input-group-text= fa_icon "map-marker"
      %span.input-group-text= t('view.shelter.latitude')
    = f.input_field :latitude, label: false, placeholder: t('view.shelter.latitude'), class: "form-control"
    = f.input_field :longitude, label: false, placeholder: t('view.shelter.longitude'), class: "form-control"
    .input-group-append
      %span.input-group-text= t('view.shelter.longitude')

app/views/admin/shelters/_fields_phone.html.haml
%fieldset
  .input-group
    .input-group-prepend
      %span.input-group-text= fa_icon "phone"
    = f.input_field :phone_number, label: false, placeholder: t('view.shelter.phone-number'), class: "form-control"
    = f.input_field :name, label: false, placeholder: t('view.shelter.name'), class: "form-control"
    .input-group-append
      = f.hidden_field :_destroy
      %button.btn.btn-outline-secondary.remove_fields= fa_icon "trash-o"

app/views/admin/shelters/_form.html.haml
%fieldset
  .input-group
    .input-group-prepend
      %span.input-group-text= t('view.shelter.title')
    = f.input_field :title, label: false, class: "form-control"
  .input-group
    .input-group-prepend
      %span.input-group-text= f.label :about
    = f.text_area :about, label: false, class:"form-control", aria:{label:"With textarea"}, rows: 5
= f.simple_fields_for :phones do |builder|
  = render partial: 'fields_phone', locals: {f: builder}
= button_add_fields fa_icon("phone"), f, :phones, 'btn btn-outline-secondary mb-3'

app/views/admin/shelters/_rform.html.haml
.custom-control.custom-checkbox
  = f.check_box :moderation, label: false, class: "custom-control-input"
  = f.label :moderation, class: "custom-control-label"
.custom-control.custom-checkbox
  = f.check_box :verified, label: false, class: "custom-control-input"
  = f.label :verified, class: "custom-control-label"
= f.input :status, as: :select, collection: Shelter.statuses.keys.collect{|s| [t("view.shelter.select.statuses.#{s.downcase}"), s]}, include_blank: false, id: :status, class: "custom-select", label: t("view.shelter.status")
.schedule
  = f.simple_fields_for :schedules do |s|
    %fieldset.mb-2
      .input-group
        .input-group-prepend
          %span.input-group-text= I18n.t("view.shelter.day_of_week.#{s.object.day_of_week}")
        = s.input_field :open, as: :time, html5: true, label: false, class: "form-control"
        = s.input_field :close, as: :time, html5: true, label: false, class: "form-control"
        = s.hidden_field :day_of_week

app/views/admin/shelters/edit.html.haml
- @page_title = "| " + t('view.title.shelter.edit')
.row.mt-4
  %section.col-6.float-left
    %h2
      %span.badge.badge-info= t('view.title.shelter.edit')
= simple_form_for @shelter, url:{controller:"admin/shelters", action:"update"} do |f|
  .row
    .col-12.col-lg-6.mt-3.mb-3
      = render partial: 'form', locals: {f: f}
      = render partial: 'fields_address', locals: {f: f}
      = f.submit t('view.button.save'), class: "btn btn-success"
      = link_to t("devise.shared.links.back"), :back
    .col-12.col-lg-6.mt-3.mb-3
      = render partial: 'rform', locals: {f: f}
.clearfix

app/views/admin/shelters/index.html.haml
.col-12.mt-3.mb-3
  %table.list
    %tr
      %th.id= sortable :id
      %th.title= sortable :title
      %th.country= sortable :country_id
      %th.moderation= sortable :moderation
      %th.verified= sortable :verified
      %th.status= sortable :status
      %th.user User
      %th.actions Actions
    - @shelters.each do |shelter|
      %tr
        %td= shelter.id
        %td= link_to shelter.title, shelter_path(shelter)
        %td= shelter.country.title
        %td= shelter.moderation
        %td= shelter.verified
        %td= shelter.status
        %td= shelter.user.username
        %td
          = link_to "e", edit_admin_shelter_path(shelter), class: "btn btn-primary btn-sm btn-circle", id:"id-#{shelter.id}"
          = link_to "v", "#", class: "btn btn-success btn-sm btn-circle"